# Form implementation generated from reading ui file 'd:\Work\code\epa2hydchart\preview.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Preview(object):
    def setupUi(self, Dialog_Preview):
        Dialog_Preview.setObjectName("Dialog_Preview")
        Dialog_Preview.resize(900, 650)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog_Preview)
        self.verticalLayout.setObjectName("verticalLayout")
        self.svgCanvas = QtWidgets.QWidget(parent=Dialog_Preview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.svgCanvas.sizePolicy().hasHeightForWidth())
        self.svgCanvas.setSizePolicy(sizePolicy)
        self.svgCanvas.setObjectName("svgCanvas")
        self.verticalLayout.addWidget(self.svgCanvas)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btn_back = QtWidgets.QPushButton(parent=Dialog_Preview)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.btn_continue = QtWidgets.QPushButton(parent=Dialog_Preview)
        self.btn_continue.setObjectName("btn_continue")
        self.horizontalLayout.addWidget(self.btn_continue)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog_Preview)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Preview)

    def retranslateUi(self, Dialog_Preview):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Preview.setWindowTitle(_translate("Dialog_Preview", "預覽"))
        self.btn_back.setText(_translate("Dialog_Preview", "返回"))
        self.btn_continue.setText(_translate("Dialog_Preview", "繼續"))
